## Gaussian elimination and finding the inverse matrix

In [1]:
import numpy as np

In [7]:
A= np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [8]:
from numpy import linalg as lag

Ainv=lag.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
b=np.array([5,11])
b

array([ 5, 11])

In [8]:
x=np.dot(Ainv,b)
x

array([1., 2.])

In [9]:
np.dot(A,x)

array([ 5., 11.])

In [11]:
np.matmul(A, Ainv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [12]:
A @ Ainv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])