## Inverse and determinant

In [4]:
import numpy as np

In [5]:
A= np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
from numpy import linalg as lng
det=lng.det(A)
det

-2.0000000000000004

In [7]:
B= np.array([[3,1],[6,2]])
B

array([[3, 1],
       [6, 2]])

In [8]:
lng.det(B)

0.0

In [23]:
np.linalg.inv(B)

LinAlgError: Singular matrix

In [9]:
Ainv = lng.inv(A)

In [10]:
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [16]:
mulAAinv=np.matmul(A, Ainv)
mulAAinv


array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [12]:
np.floor(1.0000012)

1.0

In [19]:
mulAAinv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])